apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app.kubernetes.io/instance: cloudflared-controller
    app.kubernetes.io/name: cloudflared-controller
  name: cloudflared-controller
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/instance: cloudflared-controller
      app.kubernetes.io/name: cloudflared-controller
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: cloudflared-controller
        app.kubernetes.io/name: cloudflared-controller
    spec:
      automountServiceAccountToken: true
      imagePullSecrets:
      - name: dockerconfigjson-github-com
      containers:
      - env:
        - name: TZ
          value: Europe/Berlin
        - name: CLOUDFLARE_ACCOUNT_ID
          value: ---
        - name: CLOUDFLARE_ZONE_ID
          value: ---
        - name: CLOUDFLARE_API_TOKEN
          value: ---
        image: ghcr.io/mabels/cloudflared-controller:latest
        imagePullPolicy: Always
          #livenessProbe:
          #failureThreshold: 3
          #periodSeconds: 10
          #successThreshold: 1
          #tcpSocket:
          #  port: 8384
          #timeoutSeconds: 1
        name: cloudflared-controller
          #readinessProbe:
          #failureThreshold: 3
          #periodSeconds: 10
          #successThreshold: 1
          #tcpSocket:
          #  port: 8384
          #timeoutSeconds: 1
          #startupProbe:
          #ailureThreshold: 30
          #eriodSeconds: 5
          #uccessThreshold: 1
          #cpSocket:
          # port: 8384
          #imeoutSeconds: 1
          #terminationMessagePath: /dev/termination-log
          #terminationMessagePolicy: File
          #volumeMounts:
          #- mountPath: /var/syncthing
          #name: config
      dnsPolicy: ClusterFirst
        #enableServiceLinks: true
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: cloudflared-controller
      serviceAccountName: cloudflared-controller
      terminationGracePeriodSeconds: 30
        #volumes:
        #- hostPath:
        #  path: /mam-wl-m1/syncthing
        #  type: ""
        #name: config
