apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  annotations:
  labels:
    app.kubernetes.io/instance: cloudflared-controller
    app.kubernetes.io/name: cloudflared-controller
  name: cloudflared-controller
