name: go-build

on:
  pull_request:
  push:

jobs:
  build:
    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        include:
          - platform: ubuntu-latest

    name: Build ${{ join(matrix.platform, ',') }} cloudflared-controller
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.5.0

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

      - name: Get Latest Cloudflared Version
        run: |
          node .github/workflows/query_versions.js cloudflare/cloudflared | tee -a $GITHUB_ENV

      - name: 'Get Current tag'
        id: currentTag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        with:
          prefix: v

      - name: 'Get next minor version'
        id: semvers
        uses: "WyriHaximus/github-action-next-semvers@v1"
        with:
          version: ${{ steps.currentTag.outputs.tag }}

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Check image
        run: |
          if [[ ${{ github.ref }} == refs/tags/v* ]]
          then
            CTRL_VERSION=$(echo ${{ github.ref }} | sed 's|^refs/tags/||')
            env | grep GITHUB
          else
            if [[ ${{ github.event_name }} == schedule ]]
            then
               CTRL_VERSION=v${{ steps.currentTag.outputs.tag }}
            else
               CTRL_VERSION=v${{ steps.semvers.outputs.patch }}-pre$(git rev-parse --short HEAD)
            fi
          fi
          if docker manifest inspect ghcr.io/mabels/cloudflared-controller:${CTRL_VERSION}-cfd${{ env.CLOUDFLARE_CLOUDFLARED_VERSION }}
          then
            echo "SKIP-RELEASE"
          else
            echo "RELEASE_VERSION=latest"
            echo "BUILD_VERSION=refs/tags/${CTRL_VERSION}-cfd${{ env.CLOUDFLARE_CLOUDFLARED_VERSION }}" | tee -a $GITHUB_ENV
            git tag ${CTRL_VERSION}-cfd${{ env.CLOUDFLARE_CLOUDFLARED_VERSION }}
            git push --tags
          fi

#      - name: Run GoReleaser RELEASE
#        if: ${{ env.BUILD_VERSION != '' }}
#        uses: goreleaser/goreleaser-action@v4
#        with:
#          version: ${{ env.RELEASE_VERSION }}
#          args: release --clean
#        env:
#          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
#          GITHUB_REF: ${{ env.BUILD_VERSION }}
#          CLOUDFLARE_CLOUDFLARED_VERSION: ${{ env.CLOUDFLARE_CLOUDFLARED_VERSION }}


