name: go-build

on:
  pull_request:
  push:

  workflow_dispatch:
    inputs:
      schedule:
        description: 'Simulate a schedule build'
        type: string

jobs:
  build:
    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        include:
          - platform: ubuntu-latest

    name: Build ${{ join(matrix.platform, ',') }} cloudflared-controller
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get Latest Cloudflared Version
        run: |
          node .github/workflows/query_versions.js cloudflare/cloudflared | tee -a $GITHUB_ENV

      - name: 'Get LAST_RELEASE'
        run: |
          echo "-1"
          git tag
          echo "-2"
          git tag | egrep '^v[0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*$'
          echo "-3"
          git tag | egrep '^v[0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*$' | sort -t . -k1,1n -k2,2n -k3,3n
          echo "-4"
          echo LAST_RELEASE=$(git tag  | egrep '^v[0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*$' | sort -t . -k1,1n -k2,2n -k3,3n | tail -1) | tee -a $GITHUB_ENV

      - name: 'Get next minor version'
        id: semvers
        uses: "WyriHaximus/github-action-next-semvers@v1"
        with:
          version: ${{ env.LAST_RELEASE }}

      - name: Check image
        run: |
            if [[ ${{ github.ref }} =~ ^refs/tags/v[0-9]+\.[0-9]+\.[0-9]+$ ]]
            then
              CTRL_VERSION=$(echo ${{ github.ref }} | sed 's|^refs/tags/||')
              GIT_REF=${{ github.ref }}
              echo RELEASE_TAG=latest | tee -a $GITHUB_ENV
              echo PRERELEASE=false | tee -a $GITHUB_ENV
            else
              if [ "${{ github.event_name }}" = schedule -o -n "${{ inputs.tag }}" ]
              then
                 CTRL_VERSION=v${{ env.LAST_RELEASE }}
                 GIT_REF=${{ env.LAST_RELEASE }}
                 echo RELEASE_TAG=latest | tee -a $GITHUB_ENV
                 echo PRERELEASE=false | tee -a $GITHUB_ENV
              else
                 CTRL_VERSION=v${{ steps.semvers.outputs.patch }}-pre$(git rev-parse --short HEAD)
                 GIT_REF=${{ github.ref }}
                 echo PRERELEASE=true | tee -a $GITHUB_ENV
                 echo RELEASE_TAG=dev | tee -a $GITHUB_ENV
              fi
            fi
            BUILD_VERSION=${CTRL_VERSION}-cfd${{ env.CLOUDFLARE_CLOUDFLARED_VERSION }}
            if docker manifest inspect ghcr.io/mabels/cloudflared-controller:$BUILD_VERSION
            then
              echo "SKIP-RELEASE"
            else
              echo "PUSH_TAG=needed" | tee -a $GITHUB_ENV
              echo "BUILD_VERSION=$BUILD_VERSION" | tee -a $GITHUB_ENV
              echo "CTRL_VERSION=$CTRL_VERSION" | tee -a $GITHUB_ENV
              echo "GIT_REF=$GIT_REF" | tee -a $GITHUB_ENV
            fi

      - name: Checkout Right Version
        if: ${{ env.PUSH_TAG == 'needed' }}
        uses: actions/checkout@v4
        with:
              ref: ${{ env.GIT_REF }}
              fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21

      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.10.0

      - name: Create CRDs from cloudflare-schema
        run: |
          node build-crd/build-crd.mjs > cloudflare-schema.crds.json
          kubectl apply -f cloudflare-schema.crds.json
          kubectl apply -f build-crd/access-group.example.yaml
          kubectl apply -f build-crd/cfd-tunnel.example.yaml
          kubectl apply -f build-crd/cfd-tunnel-config.example.yaml
          git diff --exit-code
          # git add cloudflare-schema.crds.json
          # git commit -am "chore: update build time cloudflare-schema.crds.json"


      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        if: ${{ env.PUSH_TAG == 'needed' }}
        uses: docker/setup-buildx-action@v3

      - name: make goreleaser happy
        if: ${{ env.PUSH_TAG == 'needed' }}
        run: |
          git tag ${{ env.BUILD_VERSION }}

      - name: Run GoReleaser RELEASE
        if: ${{ env.PUSH_TAG == 'needed' }}
        uses: goreleaser/goreleaser-action@v6
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GORELEASER_CURRENT_TAG: ${{ env.BUILD_VERSION }}
          GORELEASER_PREVIOUS_TAG: ${{ steps.currentTag.outputs.tag }}

